name: Notify Discord Every 5 Minutes

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  send-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Send message to Discord
        run: |
          curl -X POST ${{ secrets.WEBHOOK_URL }} \
          -H "Content-Type: application/json" \
          -d '{
            "content": "⏰ Bot đang chạy mỗi 5 phút 🚀"
          }'