name: Notify Discord 3PM

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  send-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Send message to Discord
        run: |
          curl -X POST ${{ secrets.WEBHOOK_URL }} \
          -H "Content-Type: application/json" \
          -d '{
            "content": "🔔 9 giờ sáng rồi! 🚀"
          }'